title: Путеводитель по переезду в Армению
author: Команда HayWiki
email: anton@haywiki.org
description: >-
  Полезная информация о переезде, жизни и легализации в Армении.
baseurl: ""
url: "https://haywiki.org"
github_username: haywiki
lang: ru
show_excerpts: true

markdown: kramdown
theme: minima
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
#  - jekyll-redirect-from
  - jekyll-relative-links
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea
  - robots.txt
sass:
  sass_dir: _sass
relative_links:
  enabled:     true
  collections: true
kramdown:
  parse_block_html: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      display_toc: true
      display_comments: true
  - scope:
      path: ""
      type: "posts"
    values:
      display_toc: false
      display_comments: true
      more_text: Читать далее

# Content variables

mir_cards_date: "27.11.2022"
